import { Inter,Roboto,Montserrat } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";

const montserrat=Montserrat({
  weight:'400',
  subsets:['latin'],
  display:'swap'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <StoreProvider>
      <body className={montserrat.className}>{children}</body>
      </StoreProvider>
    </html>
  );
}
