import { Inter,Roboto,Montserrat } from "next/font/google";
import "./globals.css";

const montserrat=Montserrat({
  weight:'500',
  subsets:['latin'],
  display:'swap'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}
